-- AI 支付风险检测：完整表结构（Docker 首次初始化）

CREATE TABLE IF NOT EXISTS `pay_risk_assess_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `source` varchar(128) DEFAULT NULL COMMENT '来源',
  `scene` varchar(128) DEFAULT NULL COMMENT '场景',
  `ip` varchar(64) DEFAULT NULL COMMENT '评估 IP',
  `risk_score` int DEFAULT NULL COMMENT '风险评分',
  `risk_level` varchar(32) DEFAULT NULL COMMENT '风险等级',
  `risk_factors_json` text COMMENT '风险因素 JSON',
  `deep_analysis` text COMMENT '深度分析',
  `payment_data_json` longtext COMMENT '输入数据 JSON',
  `ip_info_json` longtext COMMENT 'IP 情报 JSON',
  `whois_info_json` longtext COMMENT 'Whois 情报 JSON',
  `behavior_info_json` longtext COMMENT '生物行为分析 JSON',
  `topology_info_json` longtext COMMENT '关系拓扑 JSON',
  `llm_report_json` longtext COMMENT 'LLM 报告 JSON',
  `advanced_analysis_json` longtext COMMENT '高级分析 JSON',
  `agent_reflection_json` longtext COMMENT 'Agentic 反思流 JSON',
  `decision_action` varchar(32) DEFAULT NULL COMMENT '策略建议动作',
  `decision_json` text COMMENT '策略决策 JSON',
  `review_status` varchar(32) DEFAULT NULL COMMENT '人工复核状态',
  `review_remark` varchar(512) DEFAULT NULL COMMENT '复核备注',
  `reviewer` varchar(64) DEFAULT NULL COMMENT '复核人',
  `review_time` datetime DEFAULT NULL COMMENT '复核时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_risk_level` (`risk_level`),
  KEY `idx_scene` (`scene`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付风险评估记录表';

CREATE TABLE IF NOT EXISTS `pay_risk_term` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `term` varchar(256) NOT NULL COMMENT '风险词（来自聊天记录中的诈骗话术片段）',
  `category` varchar(64) DEFAULT 'OTHER' COMMENT '分类',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0 启用 1 禁用',
  `description` varchar(512) DEFAULT NULL COMMENT '说明',
  `source_type` varchar(32) NOT NULL DEFAULT 'MANUAL' COMMENT '来源',
  `hit_count` bigint NOT NULL DEFAULT 0 COMMENT '累计命中评估次数',
  `first_seen_time` datetime NOT NULL COMMENT '首次出现时间',
  `last_hit_time` datetime DEFAULT NULL COMMENT '最近命中时间',
  `first_record_id` bigint DEFAULT NULL COMMENT '首次命中的评估记录编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_term_tenant` (`term`, `tenant_id`, `deleted`),
  KEY `idx_first_seen_time` (`first_seen_time`),
  KEY `idx_status` (`status`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付风险词库';

CREATE TABLE IF NOT EXISTS `pay_risk_term_hit` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `term_id` bigint NOT NULL COMMENT '风险词编号',
  `record_id` bigint NOT NULL COMMENT '评估记录编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_term_record` (`term_id`, `record_id`, `deleted`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付风险词命中记录';
